[build]
builder = "dockerfile"
dockerfilePath = "./CaptoneProject-IOTS-SP25/CaptoneProject_IOTS_API/Dockerfile"

[deploy]
startCommand = "./CaptoneProject-IOTS-SP25/CaptoneProject_IOTS_API/CaptoneProject_IOTS_API.dll"
restartPolicyType = "always"